SELECT 
@SELECT:DIM:USER_DEF:IMPLIED:ITEM:SI.ID:ID@, 
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:SI.CODE:CODE@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:SI.NAME:NAME@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:SI.Description:Description@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:SP.ID:PerspID@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:SP.NAME:PerspName@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:SIP.ID:PlanIntl@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:SIP.NAME:PlanName@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:SI.KPI_STATUS_DEFN:StatusDefnCode@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:L1.NAME:StatusDefinition@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:SI.Item_Level:ItemLevel@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:SI.ItemStatus:ItemStatus@,
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:100*SI.KPI_STATUS:KPI_STATUS@   
 FROM  ODF_CA_STRATEGIC_ITEM SI 	  
	INNER   join ODF_CA_STRATEGIC_ITEM SIP on SIP.ID = SI.STRAT_HIERARCHY
	INNER   join odf_multi_valued_lookups mvl 		on mvl.attribute='related_kpis' 		  AND   mvl.object='strategic_item' 		  AND   mvl.value= @WHERE:PARAM:XML:INTEGER:/data/id/@value@ 		  AND   mvl.pk_id = SI.ID 	  
	INNER   join CMN_LOOKUPS_V L1 on L1.LOOKUP_TYPE = 'STRAT_ITEM_KPI_STATUS' and L1.LANGUAGE_CODE = @WHERE:PARAM:LANGUAGE@ and L1.LOOKUP_CODE = SI.KPI_STATUS_DEFN
	LEFT OUTER   join odf_ca_strat_bsc_persp sp 		on sp.id = si.bscperspective  
 WHERE   @FILTER@   AND   SI.ACTIVE = 1