SELECT   
@SELECT:DIM:USER_DEF:IMPLIED:IND:X.Dim:Dim@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.IntId:IndIntID@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.Name:IndName@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.Code:IndCode@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.Description:IndDescription@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.KPI_Periodicity:Periodicity@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.STRAT_KPI_LEVEL:IndicatorLevel@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.ITEMSTATUS:ITEMSTATUS@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.LAST_MEASURE_STATUS:LAST_MEASURE_STATUS@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.KPI_STATUS_DEFN:StatusDefinition@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.KPI_STATUS_DEFN_NAME:StatusDefinitionName@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.KPI_SIGN:Sign@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.KPI_SIGN_NAME:SignName@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.STRAT_ROLLUP_KPI:RollupMethod@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.STRAT_ROLLUP_KPI_NAME:RollupMethodName@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.IsIndicator:IsIndicator@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:IND:X.hg_has_children:hg_has_children@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.TargetValue:Target@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.CurrentValue:Measurement@,         
@SELECT:METRIC:USER_DEF:IMPLIED:round(100*X.ind_status,0):IndicatorStatus@,   
@SELECT:METRIC:USER_DEF:IMPLIED:round(100*X.ind_target_measure,0):TargetMeasure@,   
@SELECT:METRIC:USER_DEF:IMPLIED:round(100*X.ind_rollup_children,0):RollupChildren@   
 FROM      (

   Select distinct '1' @+@ SK.ID dim, SK.ID IntID, SK.CODE, SK.NAME, SK.kpi_description DESCRIPTION, SK.KPI_PERIODICITY, SK.KPI_SIGN, L1.NAME KPI_SIGN_NAME, SK.STRAT_ROLLUP_KPI, L3.NAME STRAT_ROLLUP_KPI_NAME, SK.KPI_STATUS_DEFN, L2.NAME KPI_STATUS_DEFN_NAME, SK.STRAT_KPI_LEVEL, SK.STRAT_ITEM_STATUS ITEMSTATUS, SK.LAST_MEASURE_STATUS, SK.KPI_STATUS IND_STATUS, SK.KPI_TARGET_MEASURE IND_TARGET_MEASURE, SK.KPI_ROLLUP_CHILDREN IND_ROLLUP_CHILDREN, SK.CURRENT_MEASUREMENT CurrentValue, SK.CURRENT_TARGET TargetValue, 1 IsIndicator,  
CASE WHEN (SELECT COUNT(*) FROM ODF_MULTI_VALUED_LOOKUPS MVL WHERE MVL.ATTRIBUTE = 'strat_children_kpi' and MVL.OBJECT = 'strat_kpi' and MVL.PK_ID = SK.ID) > 0 THEN '1' @+@ SK.ID ELSE NULL END hg_has_children  
 FROM  odf_ca_strat_kpi sk   
LEFT OUTER JOIN CMN_LOOKUPS_V L1 ON L1.language_code=@WHERE:PARAM:LANGUAGE@   AND   L1.lookup_type='STRAT_METRIC_SIGN'   AND   L1.lookup_Code = SK.KPI_SIGN   
LEFT OUTER JOIN CMN_LOOKUPS_V L2 ON L2.language_code=@WHERE:PARAM:LANGUAGE@   AND   L2.lookup_type='STRAT_KPI_STATUS'   AND   L2.lookup_Code = SK.KPI_STATUS_DEFN
LEFT OUTER JOIN CMN_LOOKUPS_V L3 ON L3.language_code=@WHERE:PARAM:LANGUAGE@   AND   L3.lookup_type='STRAT_ROLLUP_KPI'   AND   L3.lookup_Code = SK.STRAT_ROLLUP_KPI   
 WHERE   SK.ACTIVE = 1  AND   @NVL@(@WHERE:PARAM:USER_DEF:INTEGER:hg_row_id@,0) = 0    
 AND NOT EXISTS (SELECT 'X' FROM ODF_MULTI_VALUED_LOOKUPS MVL3 WHERE MVL3.ATTRIBUTE = 'strat_children_kpi' and MVL3.OBJECT = 'strat_kpi' and MVL3.VALUE = SK.ID)
 AND ((SK.ID = @WHERE:PARAM:USER_DEF:INTEGER:INDICATOR_INTL@) OR (@WHERE:PARAM:USER_DEF:INTEGER:INDICATOR_INTL@ is null))

 UNION

   Select distinct '1' @+@ SK.ID dim, SK.ID IntID, SK.CODE, SK.NAME, SK.kpi_description DESCRIPTION, SK.KPI_PERIODICITY, SK.KPI_SIGN, L1.NAME KPI_SIGN_NAME, SK.STRAT_ROLLUP_KPI, L3.NAME STRAT_ROLLUP_KPI_NAME, SK.KPI_STATUS_DEFN, L2.NAME KPI_STATUS_DEFN_NAME, SK.STRAT_KPI_LEVEL, SK.STRAT_ITEM_STATUS ITEMSTATUS, SK.LAST_MEASURE_STATUS,SK.KPI_STATUS IND_STATUS, SK.KPI_TARGET_MEASURE IND_TARGET_MEASURE, SK.KPI_ROLLUP_CHILDREN IND_ROLLUP_CHILDREN, SK.CURRENT_MEASUREMENT CurrentValue, SK.CURRENT_TARGET TargetValue, 1 IsIndicator,  
CASE WHEN (SELECT COUNT(*) FROM ODF_MULTI_VALUED_LOOKUPS MVL WHERE MVL.ATTRIBUTE = 'strat_children_kpi' and MVL.OBJECT = 'strat_kpi' and MVL.PK_ID = SK.ID) > 0 THEN '1' @+@ SK.ID ELSE NULL END hg_has_children  
 FROM  odf_ca_strat_kpi sk   
INNER   join ODF_MULTI_VALUED_LOOKUPS MVL2 ON MVL2.ATTRIBUTE = 'strat_children_kpi' and MVL2.OBJECT = 'strat_kpi' and MVL2.VALUE = SK.ID AND MVL2.PK_ID = substr(@WHERE:PARAM:USER_DEF:INTEGER:hg_row_id@,2)
LEFT OUTER JOIN CMN_LOOKUPS_V L1 ON L1.language_code=@WHERE:PARAM:LANGUAGE@   AND   L1.lookup_type='STRAT_METRIC_SIGN'   AND   L1.lookup_Code = SK.KPI_SIGN   
LEFT OUTER JOIN CMN_LOOKUPS_V L2 ON L2.language_code=@WHERE:PARAM:LANGUAGE@   AND   L2.lookup_type='STRAT_KPI_STATUS'   AND   L2.lookup_Code = SK.KPI_STATUS_DEFN
LEFT OUTER JOIN CMN_LOOKUPS_V L3 ON L3.language_code=@WHERE:PARAM:LANGUAGE@   AND   L3.lookup_type='STRAT_ROLLUP_KPI'   AND   L3.lookup_Code = SK.STRAT_ROLLUP_KPI   
 WHERE   SK.ACTIVE = 1  AND   substr(@WHERE:PARAM:USER_DEF:INTEGER:hg_row_id@,1,1)='1' 
 ) X 
 WHERE   @FILTER@
 AND  @WHERE:SECURITY:STRAT_KPI:X.INTID@