SELECT   
@SELECT:DIM:USER_DEF:IMPLIED:ITEM:X.Dim:Dim@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.IntId:ItemIntID@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.Name:ItemName@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.Code:ItemCode@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.Description:ItemDescription@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.STRAT_MEAS_PER:MeasurementPeriod@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.MEASUREMENTPERIOD:MeasurementPeriodName@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.STRAT_KPI_LEVEL:IndicatorLevel@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.ITEMSTATUS:IndicatorStatus@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.KPI_STATUS_DEFN:StatusDefinition@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.KPI_STATUS_DEFN_NAME:StatusDefinitionName@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.KPI_SIGN:Sign@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.KPI_SIGN_NAME:SignName@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.STRAT_ROLLUP_KPI:RollupMethod@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.STRAT_ROLLUP_KPI_NAME:RollupMethodName@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.IsKPI:IsKPI@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.hg_has_children:HasChildren@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.TargetValue:Target@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.CurrentValue:Measurement@,         
@SELECT:METRIC:USER_DEF:IMPLIED:round(100*X.kpi_status,0):IndicatorPercentStatus@,   
@SELECT:METRIC:USER_DEF:IMPLIED:round(100*X.kpi_target_measure,0):TargetMeasure@,   
@SELECT:METRIC:USER_DEF:IMPLIED:round(100*X.kpi_rollup_children,0):RollupChildren@   
 FROM      (

   Select distinct '1'||SK.ID dim, SK.ID IntID, SK.CODE, SK.NAME, SK.kpi_description DESCRIPTION, SK.STRAT_MEAS_PER, L4.NAME MEASUREMENTPERIOD, SK.KPI_SIGN, L1.NAME KPI_SIGN_NAME, SK.STRAT_ROLLUP_KPI, L3.NAME STRAT_ROLLUP_KPI_NAME, SK.KPI_STATUS_DEFN, L2.NAME KPI_STATUS_DEFN_NAME, Null ScopeId, Null ScopeName, SK.STRAT_KPI_LEVEL, SK.STRAT_ITEM_STATUS ITEMSTATUS, SK.KPI_STATUS, SK.KPI_TARGET_MEASURE, SK.KPI_ROLLUP_CHILDREN, SK.CURRENT_MEASUREMENT CurrentValue, SK.CURRENT_TARGET TargetValue, 1 isKPI,  
		CASE WHEN (SELECT COUNT(*) FROM ODF_MULTI_VALUED_LOOKUPS MVL WHERE MVL.ATTRIBUTE = 'strat_children_kpi' and MVL.OBJECT = 'strat_kpi' and MVL.PK_ID = SK.ID) > 0 THEN '1'||SK.ID ELSE NULL END hg_has_children  
 FROM  odf_ca_strat_kpi sk    
	LEFT OUTER JOIN CMN_LOOKUPS_V L1 ON L1.language_code=@WHERE:PARAM:LANGUAGE@   AND   L1.lookup_type='STRAT_METRIC_SIGN'   AND   L1.lookup_Code = SK.KPI_SIGN   
	LEFT OUTER JOIN CMN_LOOKUPS_V L2 ON L2.language_code=@WHERE:PARAM:LANGUAGE@   AND   L2.lookup_type='STRAT_KPI_STATUS'   AND   L2.lookup_Code = SK.KPI_STATUS_DEFN
	LEFT OUTER JOIN CMN_LOOKUPS_V L3 ON L3.language_code=@WHERE:PARAM:LANGUAGE@   AND   L3.lookup_type='STRAT_ROLLUP_KPI'   AND   L3.lookup_Code = SK.STRAT_ROLLUP_KPI   
	LEFT OUTER JOIN CMN_LOOKUPS_V L4 ON L4.language_code=@WHERE:PARAM:LANGUAGE@   AND   L4.lookup_type='STRAT_IND_MEAS_PER'   AND   L4.lookup_Code = SK.STRAT_MEAS_PER   
 WHERE   SK.ACTIVE = 1  AND   nvl(@WHERE:PARAM:USER_DEF:INTEGER:hg_row_id@,0) = 0    
 AND SK.ID = @WHERE:PARAM:XML:INTEGER:/data/id/@value@ 
 UNION

   Select distinct '1'||SK.ID dim, SK.ID IntID, SK.CODE, SK.NAME, SK.kpi_description DESCRIPTION, SK.STRAT_MEAS_PER, L4.NAME MEASUREMENTPERIOD, SK.KPI_SIGN, L1.NAME KPI_SIGN_NAME, SK.STRAT_ROLLUP_KPI, L3.NAME STRAT_ROLLUP_KPI_NAME, SK.KPI_STATUS_DEFN, L2.NAME KPI_STATUS_DEFN_NAME, Null ScopeId, Null ScopeName, SK.STRAT_KPI_LEVEL, SK.STRAT_ITEM_STATUS ITEMSTATUS, SK.KPI_STATUS, SK.KPI_TARGET_MEASURE, SK.KPI_ROLLUP_CHILDREN, SK.CURRENT_MEASUREMENT CurrentValue, SK.CURRENT_TARGET TargetValue, 1 isKPI,  
		CASE WHEN (SELECT COUNT(*) FROM ODF_MULTI_VALUED_LOOKUPS MVL WHERE MVL.ATTRIBUTE = 'strat_children_kpi' and MVL.OBJECT = 'strat_kpi' and MVL.PK_ID = SK.ID) > 0 THEN '1'||SK.ID ELSE NULL END hg_has_children  
 FROM  odf_ca_strat_kpi sk    
	INNER   join ODF_MULTI_VALUED_LOOKUPS MVL2 ON MVL2.ATTRIBUTE = 'strat_children_kpi' and MVL2.OBJECT = 'strat_kpi' and MVL2.VALUE = SK.ID AND MVL2.PK_ID = substr(@WHERE:PARAM:USER_DEF:INTEGER:hg_row_id@,2)
	LEFT OUTER JOIN CMN_LOOKUPS_V L1 ON L1.language_code=@WHERE:PARAM:LANGUAGE@   AND   L1.lookup_type='STRAT_METRIC_SIGN'   AND   L1.lookup_Code = SK.KPI_SIGN   
	LEFT OUTER JOIN CMN_LOOKUPS_V L2 ON L2.language_code=@WHERE:PARAM:LANGUAGE@   AND   L2.lookup_type='STRAT_KPI_STATUS'   AND   L2.lookup_Code = SK.KPI_STATUS_DEFN
	LEFT OUTER JOIN CMN_LOOKUPS_V L3 ON L3.language_code=@WHERE:PARAM:LANGUAGE@   AND   L3.lookup_type='STRAT_ROLLUP_KPI'   AND   L3.lookup_Code = SK.STRAT_ROLLUP_KPI   
	LEFT OUTER JOIN CMN_LOOKUPS_V L4 ON L4.language_code=@WHERE:PARAM:LANGUAGE@   AND   L4.lookup_type='STRAT_IND_MEAS_PER'   AND   L4.lookup_Code = SK.STRAT_MEAS_PER   

 WHERE   SK.ACTIVE = 1  AND     substr(@WHERE:PARAM:USER_DEF:INTEGER:hg_row_id@,1,1)='1'      

 ) X 
 WHERE   @FILTER@