SELECT   
@SELECT:DIM:USER_DEF:IMPLIED:ITEM:X.Dim:Dim@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.IntId:ItemIntID@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.Name:ItemName@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.Code:ItemCode@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.Description:ItemDescription@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.Weight:Weight@,     
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:round(X.WeightPercent * 100,0):WeightPercent@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:round(X.STRAT_ALLOC_PERC * 100,0):FundsAllocationPercentage@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.ITEM_LEVEL:ITEM_LEVEL@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.PerspId:PerspId@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.Perspective:Perspective@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.ItemStatus:ItemStatus@,         
@SELECT:DIM_PROP:USER_DEF:IMPLIED:ITEM:X.hg_has_children:hg_has_children@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_TD_REC_BEN:TopDownExpectedBenefit@,
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_TD_BENEFIT:TopDownBenefit@,
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_TD_REC_BEN-X.STRAT_TD_BENEFIT:UnexpectedBenefit@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_ALLOC_BENEFIT:AllocatedBenefit@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_TD_BENEFIT-X.STRAT_ALLOC_BENEFIT:UnallocatedBenefit@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_COMMIT_BENEFIT:CommittedBenefit@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_ALLOC_BENEFIT-X.STRAT_COMMIT_BENEFIT:UncommittedBenefit@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_TD_REC_FUND:TopDownReceivedFunding@,
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_TOP_DOWN_FUND:TopDownFunding@,
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_TD_REC_FUND-X.STRAT_TOP_DOWN_FUND:UnusedFunding@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_ALLOC_FUNDING:AllocatedFunding@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_COMMIT_FUNDING:CommittedFunding@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_ALLOC_FUNDING-X.STRAT_COMMIT_FUNDING:UncommittedFunding@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_TOP_DOWN_FUND-X.STRAT_ALLOC_FUNDING:UnallocatedFunding@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_TD_REC_FTE:TopDownReceivedFTE@,
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_TD_FTE:TopDownFTE@,
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_TD_REC_FTE-X.STRAT_TD_FTE:UnusedFTE@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_ALLOC_FTE:AllocatedFTE@,         
@SELECT:METRIC:USER_DEF:IMPLIED:X.STRAT_TD_FTE-X.STRAT_ALLOC_FTE:UnallocatedFTE@,         
@SELECT:METRIC:USER_DEF:IMPLIED:round(100*X.kpi_status,0):Variation@   
FROM      (select distinct '1' @+@ SI.ID dim,      SI.ID IntID, SI.CODE, SI.NAME, SI.DESCRIPTION,      SP.ID PerspID, SP.NAME Perspective, 	  
			SI.ITEM_LEVEL, SI.WEIGHT, SI.WEIGHTPERCENT, SI.STRAT_ALLOC_PERC, SI.kpi_status, SI.ITEMSTATUS, 
			SI.STRAT_TD_REC_BEN, SI.STRAT_TD_BENEFIT, SI.STRAT_ALLOC_BENEFIT, SI.STRAT_COMMIT_BENEFIT, 
			SI.STRAT_TD_REC_FUND, SI.STRAT_TOP_DOWN_FUND, SI.STRAT_ALLOC_FUNDING, SI.STRAT_COMMIT_FUNDING, 
			SI.STRAT_TD_REC_FTE, SI.STRAT_TD_FTE, SI.STRAT_ALLOC_FTE, 
			CASE WHEN ((SELECT COUNT(*) 			  
						FROM  ODF_CA_STRATEGIC_ITEM SI2 				  
						WHERE   SI2.PARENTITEM = SI.ID)
						) > 0             
						THEN '1' @+@ SI.ID ELSE NULL END hg_has_children  
			FROM  odf_ca_strategic_item SI     
				LEFT OUTER   join odf_ca_strat_bsc_persp sp on sp.id = si.bscperspective  
			WHERE   SI.ID = @WHERE:PARAM:USER_DEF:INTEGER:STRAT_HIER@  AND   SI.ACTIVE =1   AND   @NVL@(@WHERE:PARAM:USER_DEF:INTEGER:hg_row_id@,0) = 0  
			UNION  
			Select distinct '1' @+@ SI.ID dim, SI.ID IntID, SI.CODE, SI.NAME, SI.DESCRIPTION,      SP.ID PerspID, SP.NAME Perspective, 	  
			SI.ITEM_LEVEL, SI.WEIGHT, SI.WEIGHTPERCENT, SI.STRAT_ALLOC_PERC, SI.kpi_status, SI.ITEMSTATUS, 
			SI.STRAT_TD_REC_BEN, SI.STRAT_TD_BENEFIT, SI.STRAT_ALLOC_BENEFIT, SI.STRAT_COMMIT_BENEFIT, 
			SI.STRAT_TD_REC_FUND, SI.STRAT_TOP_DOWN_FUND, SI.STRAT_ALLOC_FUNDING, SI.STRAT_COMMIT_FUNDING, 
			SI.STRAT_TD_REC_FTE, SI.STRAT_TD_FTE, SI.STRAT_ALLOC_FTE, 
			CASE WHEN ((SELECT COUNT(*) 			  
						FROM  ODF_CA_STRATEGIC_ITEM SI2 				  
						WHERE   SI2.PARENTITEM = SI.ID)
						) > 0             
						THEN '1' @+@ SI.ID ELSE NULL END hg_has_children  
			FROM  odf_ca_strategic_item SI    
				LEFT OUTER   join odf_ca_strat_bsc_persp sp on sp.id = si.bscperspective  
			WHERE   SI.PARENTITEM=substr(@WHERE:PARAM:USER_DEF:INTEGER:hg_row_id@,2)   AND   SI.ACTIVE =1   AND   substr(@WHERE:PARAM:USER_DEF:INTEGER:hg_row_id@,1,1)='1'  
			) X  
WHERE   @FILTER@